// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type ListingFee struct {
	ID             uuid.UUID
	PolicyID       uuid.UUID
	PublicKey      string
	TargetPluginID string
	Amount         string
	Destination    string
	TxHash         *string
	BlockNumber    *int64
	Confirmations  int32
	Status         string
	SubmittedAt    *time.Time
	PaidAt         *time.Time
	FailureReason  *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type PluginPolicy struct {
	ID                 uuid.UUID
	Active             bool
	DeactivationReason *string
}

type TxIndexer struct {
	ID            uuid.UUID
	PolicyID      uuid.UUID
	StatusOnchain string
	Lost          bool
}
